# Generated by Django 4.2.3 on 2023-08-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Completed Date")),
                (
                    "actions",
                    models.CharField(
                        choices=[
                            ("C", "Charged Batteries"),
                            ("G", "Greased"),
                            ("B", "Balanced Prop"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "rc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.remotecontrolvehicle",
                    ),
                ),
            ],
        ),
    ]
