# Generated by Django 4.2.3 on 2023-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_battery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battery",
            name="Cells",
            field=models.IntegerField(),
        ),
    ]
