# Generated by Django 4.2.3 on 2023-08-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_alter_battery_cells"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotecontrolvehicle",
            name="batterys",
            field=models.ManyToManyField(to="main_app.battery"),
        ),
    ]
